### ISSUE TITLE
Unable to Deploy alfresco-android-app

### ISSUE THREAD

**Issue by adctzm** [Alfresco/alfresco-android-app#311]
Hi, 

I succeed to build and package Alfresco-android-app release 1.5.1 using Android Studio 1.2.1.1 and Gradle v2.2.1. I installed it on my mobile. However when I tried to configure access to:
- local community alfresco server, I got the following crash "Alfresco s'est arrêté" and the application was closed automatically.
-  alfresco cloud, I got the following error "Authentication Failed" (Despite I was able to access using web access)

What should I do from my side to resolve the issue?
Thank you in advance

**Comment by jmpascal** [comment]
Hello,

The first thing to do is to discover the stacktrace associated when the app crashes.

You can find it in the logcat view (Android tab). It might appears in red. It will help to find the root of your problem.

For information : 
https://developer.android.com/tools/debugging/debugging-studio.html

**Comment by adctzm** [comment]
Here the log when the android application crashes:
05-24 14:56:36.363    1970-2207/? E/Watchdog﹕ !@Sync 1421
05-24 14:56:47.084   5930-23091/? E/MM_DEVICE﹕ mm_device_thread loop break
05-24 14:56:47.144  19868-19868/org.alfresco.mobile.android.application E/ActivityThread﹕ Failed to find provider info for org.alfresco.mobile.android.provider.debug.operations
05-24 14:56:47.184  19868-19868/org.alfresco.mobile.android.application E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: Unknown URL content://org.alfresco.mobile.android.provider.debug.operations/operations
            at android.content.ContentResolver.insert(ContentResolver.java:871)
            at org.alfresco.mobile.android.async.impl.BaseOperationRequest.generateNotificationUri(BaseOperationRequest.java:63)
            at org.alfresco.mobile.android.async.OperationRequest.<init>(OperationRequest.java:84)
            at org.alfresco.mobile.android.async.impl.BaseOperationRequest.<init>(BaseOperationRequest.java:47)
            at org.alfresco.mobile.android.async.account.CreateAccountRequest.<init>(CreateAccountRequest.java:52)
            at org.alfresco.mobile.android.async.account.CreateAccountRequest$Builder.build(CreateAccountRequest.java:130)
            at org.alfresco.mobile.android.async.account.CreateAccountRequest$Builder.build(CreateAccountRequest.java:78)
            at org.alfresco.mobile.android.async.OperationCreator.execute(OperationCreator.java:121)
            at org.alfresco.mobile.android.async.OperationCreator.execute(OperationCreator.java:107)
            at org.alfresco.mobile.android.async.Operator.load(Operator.java:110)
            at org.alfresco.mobile.android.application.fragments.account.AccountEditFragment.validateServer(AccountEditFragment.java:194)
            at org.alfresco.mobile.android.application.fragments.account.AccountEditFragment.access$000(AccountEditFragment.java:61)
            at org.alfresco.mobile.android.application.fragments.account.AccountEditFragment$1.onClick(AccountEditFragment.java:111)
            at android.view.View.performClick(View.java:4439)
            at android.widget.Button.performClick(Button.java:139)
            at android.view.View$PerformClick.run(View.java:18395)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5317)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
05-24 14:56:47.404   1463-12412/? E/hawaii.gralloc﹕ GRALLOC ALLOC flags 933

Note that I tried to connect to an alfresco community server that is deployed on my private cloud (I used a private IP address). 
Any idea about the crash root cause?
Thank you in advance

**Comment by jmpascal** [comment]
Have you tried to uninstall & reinstall the application ?

**Comment by adctzm** [comment]
Hi, 
Yes I already uninstall it before reinstalling it :(

**Comment by jmpascal** [comment]
Could you confirm you use **customRelease** as Build Variant as defined in https://github.com/Alfresco/alfresco-android-app/wiki/Getting-Started

**Comment by adctzm** [comment]
Yes I run it using customRelease as described in the following figure:
![capture](https://cloud.githubusercontent.com/assets/12563485/7810594/3a8c5fb8-039b-11e5-8e30-610a6ffc8431.PNG)

**Comment by adctzm** [comment]
Hi, 
Any update on the following incident?
Thank you in advance for your support
Regards, 
Aymen

**Comment by adctzm** [comment]
Hi,

Any update on this ?

Cheers, 
Aymen

**Comment by adctzm** [comment]
Hi again,
Any update on this ?

Aymen

**Comment by adctzm** [comment]
Any update on this please ?

**Comment by jmpascal** [comment]
Aloah, 

Sorry for the long dealy. I was mostly focused on the release of our new Android Activiti Application.

The issue you encounter is due to a lack of documentation that has been fixed now.

The application can be build on Debug Mode or Release Mode. 
* In Debug buildVariants are **debug** and **customDebug**.
* In Release buildVariants are **release** & **customRelease**.

But I forget to mention you need also to change a key in gradle.properties from debug to release.

To solve your issue you need to configure the type in gradle.properties
* Open **gradle.properties** file
* Find **DEFAULT_PUBLISH** key and replace **debug** value by **release** 

If you want to revert to debug mode, replace variants and the key.

Hope it helps.

**Comment by adctzm** [comment]
Hi 
Thank you for the update however i still have the crash with the following exception stach trace:

06-21 12:59:22.115  17073-17073/? D/AndroidRuntime﹕ Shutting down VM
06-21 12:59:22.115  17073-17073/? W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40f47960)
06-21 12:59:22.135  17073-17073/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{Alfresco.mobile.android/org.alfresco.mobile.android.application.activity.MainActivity}: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2255)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309)
            at android.app.ActivityThread.access$700(ActivityThread.java:157)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5317)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at net.hockeyapp.android.utils.Util.sanitizeAppIdentifier(Util.java:144)
            at net.hockeyapp.android.UpdateManager.register(UpdateManager.java:107)
            at net.hockeyapp.android.UpdateManager.register(UpdateManager.java:94)
            at net.hockeyapp.android.UpdateManager.register(UpdateManager.java:82)
            at net.hockeyapp.android.UpdateManager.register(UpdateManager.java:71)
            at org.alfresco.mobile.android.application.extension.hockeyapp.HockeyAppManagerImpl.checkForUpdates(HockeyAppManagerImpl.java:60)
            at org.alfresco.mobile.android.ui.activity.AlfrescoActivity.onCreate(AlfrescoActivity.java:96)
            at org.alfresco.mobile.android.application.activity.BaseActivity.onCreate(BaseActivity.java:55)
            at org.alfresco.mobile.android.application.activity.MainActivity.onCreate(MainActivity.java:160)
            at android.app.Activity.performCreate(Activity.java:5326)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2218)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309)
            at android.app.ActivityThread.access$700(ActivityThread.java:157)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5317)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)

Can you help please?

Thank you in advance for your support

Regards, 
Aymen

**Comment by jmpascal** [comment]
Just comment in file**alfresco-android-app\build.gradle**
```
debugCompile project(':extensions:hockeyapp')
```

**Comment by kevloppeur93** [comment]
hi adctzm the solution who gives you jmpascal run?
